spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/delsat_inventory?serverTimezone=America/Argentina/Buenos_Aires&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:

logging:
  level:
    org:
      hibernate:
        SQL: debug

